"""association cascade update

Revision ID: 5495addc82c2
Revises: e4756db40b04
Create Date: 2025-05-26 02:36:52.421633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5495addc82c2'
down_revision: Union[str, None] = 'e4756db40b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('a_gifs_roles_role_pk_fkey', 'a_gifs_roles', type_='foreignkey')
    op.drop_constraint('a_gifs_roles_gif_uid_fkey', 'a_gifs_roles', type_='foreignkey')
    op.create_foreign_key(None, 'a_gifs_roles', 'roles', ['role_pk'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_gifs_roles', 'gifs', ['gif_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_gifs_tags_gif_uid_fkey', 'a_gifs_tags', type_='foreignkey')
    op.drop_constraint('a_gifs_tags_tag_pk_fkey', 'a_gifs_tags', type_='foreignkey')
    op.create_foreign_key(None, 'a_gifs_tags', 'tags', ['tag_pk'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_gifs_tags', 'gifs', ['gif_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_images_roles_image_uid_fkey', 'a_images_roles', type_='foreignkey')
    op.drop_constraint('a_images_roles_role_pk_fkey', 'a_images_roles', type_='foreignkey')
    op.create_foreign_key(None, 'a_images_roles', 'roles', ['role_pk'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_images_roles', 'images', ['image_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_images_tags_tag_pk_fkey', 'a_images_tags', type_='foreignkey')
    op.drop_constraint('a_images_tags_image_uid_fkey', 'a_images_tags', type_='foreignkey')
    op.create_foreign_key(None, 'a_images_tags', 'images', ['image_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_images_tags', 'tags', ['tag_pk'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_manga_tags_manga_uid_fkey', 'a_manga_tags', type_='foreignkey')
    op.drop_constraint('a_manga_tags_tag_pk_fkey', 'a_manga_tags', type_='foreignkey')
    op.create_foreign_key(None, 'a_manga_tags', 'mangas', ['manga_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_manga_tags', 'tags', ['tag_pk'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_videos_roles_role_pk_fkey', 'a_videos_roles', type_='foreignkey')
    op.drop_constraint('a_videos_roles_gif_uid_fkey', 'a_videos_roles', type_='foreignkey')
    op.create_foreign_key(None, 'a_videos_roles', 'roles', ['role_pk'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_videos_roles', 'videos', ['gif_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('a_videos_tags_gif_uid_fkey', 'a_videos_tags', type_='foreignkey')
    op.drop_constraint('a_videos_tags_tags_pk_fkey', 'a_videos_tags', type_='foreignkey')
    op.create_foreign_key(None, 'a_videos_tags', 'tags', ['tags_pk'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'a_videos_tags', 'videos', ['gif_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'a_videos_tags', type_='foreignkey')
    op.drop_constraint(None, 'a_videos_tags', type_='foreignkey')
    op.create_foreign_key('a_videos_tags_tags_pk_fkey', 'a_videos_tags', 'tags', ['tags_pk'], ['uid'])
    op.create_foreign_key('a_videos_tags_gif_uid_fkey', 'a_videos_tags', 'videos', ['gif_uid'], ['uid'])
    op.drop_constraint(None, 'a_videos_roles', type_='foreignkey')
    op.drop_constraint(None, 'a_videos_roles', type_='foreignkey')
    op.create_foreign_key('a_videos_roles_gif_uid_fkey', 'a_videos_roles', 'videos', ['gif_uid'], ['uid'])
    op.create_foreign_key('a_videos_roles_role_pk_fkey', 'a_videos_roles', 'roles', ['role_pk'], ['uid'])
    op.drop_constraint(None, 'a_manga_tags', type_='foreignkey')
    op.drop_constraint(None, 'a_manga_tags', type_='foreignkey')
    op.create_foreign_key('a_manga_tags_tag_pk_fkey', 'a_manga_tags', 'tags', ['tag_pk'], ['uid'])
    op.create_foreign_key('a_manga_tags_manga_uid_fkey', 'a_manga_tags', 'mangas', ['manga_uid'], ['uid'])
    op.drop_constraint(None, 'a_images_tags', type_='foreignkey')
    op.drop_constraint(None, 'a_images_tags', type_='foreignkey')
    op.create_foreign_key('a_images_tags_image_uid_fkey', 'a_images_tags', 'images', ['image_uid'], ['uid'])
    op.create_foreign_key('a_images_tags_tag_pk_fkey', 'a_images_tags', 'tags', ['tag_pk'], ['uid'])
    op.drop_constraint(None, 'a_images_roles', type_='foreignkey')
    op.drop_constraint(None, 'a_images_roles', type_='foreignkey')
    op.create_foreign_key('a_images_roles_role_pk_fkey', 'a_images_roles', 'roles', ['role_pk'], ['uid'])
    op.create_foreign_key('a_images_roles_image_uid_fkey', 'a_images_roles', 'images', ['image_uid'], ['uid'])
    op.drop_constraint(None, 'a_gifs_tags', type_='foreignkey')
    op.drop_constraint(None, 'a_gifs_tags', type_='foreignkey')
    op.create_foreign_key('a_gifs_tags_tag_pk_fkey', 'a_gifs_tags', 'tags', ['tag_pk'], ['uid'])
    op.create_foreign_key('a_gifs_tags_gif_uid_fkey', 'a_gifs_tags', 'gifs', ['gif_uid'], ['uid'])
    op.drop_constraint(None, 'a_gifs_roles', type_='foreignkey')
    op.drop_constraint(None, 'a_gifs_roles', type_='foreignkey')
    op.create_foreign_key('a_gifs_roles_gif_uid_fkey', 'a_gifs_roles', 'gifs', ['gif_uid'], ['uid'])
    op.create_foreign_key('a_gifs_roles_role_pk_fkey', 'a_gifs_roles', 'roles', ['role_pk'], ['uid'])
    # ### end Alembic commands ###
